service:
  apiversion: "v1"

configmap:
  apiversion: "v1"

enabled: true
image: ""
imageTag: ""
SPRING_PROFILES_ACTIVE: ""
tenants: ""
secret:
  apiversion: "v1"
  datasource:
    username: "mifos"
    password: "password"
    host: "operationsmysql"
    port: 3306
    schema: "tenants"
limits:
  cpu: "1000m"
  memory: "1024M"
requests:
  cpu: "500m"
  memory: "512M"    
# Enabling this will publicly expose your Elasticsearch instance.
# Only enable this if you have security enabled on your cluster
ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: "nginx"
  pathtype: ImplementationSpecific
  hosts:
    - host: "" 
      paths:
        - path: /
  tls: []
  #  - secretName: sandbox-secret
  #    hosts:
  #      - chart-example.local
deployment:
  apiVersion: "apps/v1"
  annotations:
    deployTime: "{{ .Values.deployTime }}"